#pragma once
#define WINDOW_WIDTH 768
#define WINDOW_HEIGHT 512
#define DEFAULT_DRAW_COLOR 68, 202, 255, 0
#define FPS 60
#define CRANE_VELOCITY 8
#define PLAYER_VELOCITY 7
#define VERTICAL_VELOCITY 12
#define NUMBER_OF_COLUMNS 12
#define NUMBER_OF_ROWS 6
#define MAXIMUM_NUMBER_OF_BLOCKS_ON_COLUMN 6
#define BLOCK_WIDTH 64
